### ISSUE TITLE
Disabling fullbright doesn't allow brightness below 50%

### ISSUE THREAD

**Issue by FoilGear** [Dillon8775/Simple-Keybinds#1]
If one disables full-bright, then attempts to slide the brightness slider (gamma in options.txt) all the way down to zero (0), the game will not reflect this and switch it back to 0.5 instead (%50 brightness).
This impacts me as a player who prefers the moodiness of the game at its lowest gamma, but I want to keep this mod for its ability to bind keys to 'display chunk grids' and 'display hit-boxes'.

**Comment by Dillon8775** [comment]
Thank you for the feedback! I have released a new version (for Minecraft 1.16.5 all the way through 1.21.1), which allows you to move the brightness slider all the way down to 0 (moody)!
You can find them on the mod's CurseForge page, Modrinth page, or this Github release's page (it may take me a bit to get the files up onto CurseForge and Modrinth, but I always release new versions on Github first).
If you have another other suggestions, let me know! :)
